#!/bin/bash

install() {
  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # prepare vars
  local name="buildkit"
  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./bin/buildctl"

  # prepare context
  cd $tmp_dir

  # reference: https://github.com/moby/buildkit/releases
  # example:
  #   https://github.com/moby/buildkit/releases/download/v0.10.6/buildkit-v0.10.6.darwin-arm64.tar.gz
  #   https://github.com/moby/buildkit/releases/download/v0.10.6/buildkit-v0.10.6.darwin-amd64.tar.gz
  # generate url
  local url="https://github.com/moby/buildkit/releases/download/$PACKAGE_CORE_VERSION/${name}-${PACKAGE_CORE_VERSION}.${platform}-${arch}.tar.gz"
  log::debug "[package][$name][$kernel][$arch] url: $url"

  # download
  os::download $tmp_file $url

  # extract
  tar -zxvf $tmp_file >>/dev/null 2>&1

  # install
  #
  # bin
  # ├── buildctl
  # ├── buildkit-qemu-aarch64
  # ├── buildkit-qemu-arm
  # ├── buildkit-qemu-i386
  # ├── buildkit-qemu-mips64
  # ├── buildkit-qemu-mips64el
  # ├── buildkit-qemu-ppc64le
  # ├── buildkit-qemu-riscv64
  # ├── buildkit-qemu-s390x
  # ├── buildkit-runc
  # └── buildkitd
  #
  sudo cp -rf ./bin/* $usr_bin_dir

  # alias
  sudo ln -sf $usr_bin_dir/buildctl $usr_bin_dir/$name

  # clean
  rm -rf $tmp_dir
}

export -f install
